#!/bin/bash -e

rev=${1:-latest}

docker run --name build_spigot -v "$PWD/tmp:/data" -it ubuntu:latest bash -c "
apt update
apt install -y software-properties-common
apt-add-repository -y 'deb http://security.debian.org/debian-security stretch/updates main'
apt update
apt install -y wget git openjdk-20-jre-headless

cd /data

git config --global --unset core.autocrlf

wget -qO BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

java -Xmx4096M -jar BuildTools.jar --rev $rev
"

cp -r $PWD/tmp/spigot-$rev.jar $PWD/server/server.jar
