version: '3.7'
services:
  server:
    build:
      context: '.'
    user: '1000:1000'
    image: '${SERVER_HOST}'
    container_name: '${SERVER_HOST}'
    depends_on:
      - 'postgres'
    env_file:
      - '.env/${ENV}.env'
    restart: 'unless-stopped'
    ports:
      - '${EXPOSE_SERVER}:${SERVER_PORT}'
      - '${EXPOSE_DYNMAP}:${DYNMAP_PORT}'
    networks:
      - 'minecraft'
    volumes:
      - '${PWD}/server:/app'
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '1m'
networks:
  minecraft:
    name: '${NETWORK_NAME}'
    driver: 'bridge'
